/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class darksword_ravel_RavelControl */

#ifndef _Included_darksword_ravel_RavelControl
#define _Included_darksword_ravel_RavelControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     darksword_ravel_RavelControl
 * Method:    connect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_darksword_ravel_RavelControl_connect
  (JNIEnv *, jclass, jstring);

/*
 * Class:     darksword_ravel_RavelControl
 * Method:    simulate
 * Signature: (Ljava/lang/String;[I[BIZ)I
 */
JNIEXPORT jint JNICALL Java_darksword_ravel_RavelControl_simulate
  (JNIEnv *, jclass, jstring, jstring, jintArray, jbyteArray, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
